### ISSUE TITLE
There seems to be something wrong with the contents of the nginx.conf

### ISSUE THREAD

**Issue by geovey** [dabamos/openadms-server#2]
nginx: [emerg] "location" directive is not allowed here in /usr/local/nginx/openadms-server/api.conf:34
nginx: configuration file /usr/local/nginx/nginx.conf test failed

Is it because the position of the following statement in the nginx.conf file is incorrect and there is an extra "}" match？

        # Include the OpenADMS Server API and HTTP status code configuration.
        include openadms-server/api.conf;
        include openadms-server/status.conf;
    **}**
}

**Comment by interkosmos** [comment]
Thank you for reporting, has been fixed.
